site_name: Calligraph
site_url: https://calligraph.readthedocs.io/
copyright: Copyright &copy; since 2024 <a href="https://github.com/calliope-project/calligraph/graphs/contributors">Calligraph contributors</a> (Apache 2.0 licensed)
repo_url: https://github.com/calliope-project/calligraph
hooks:
  - docs/hooks/changelog_highlight.py
theme:
  font:
    text: Lato
    code: Source Code Pro
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate
  logo: img/logo-bw.png
  favicon: img/favicon.ico
extra_css:
  - css/extra.css
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_bases: true
            filters:
              - "!^_"
            heading_level: 1
            show_root_heading: true
            merge_init_into_class: true
            show_if_no_docstring: true
            signature_crossrefs: true
            show_root_toc_entry: false
            show_signature_annotations: false
            inherited_members: true
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
            - https://docs.xarray.dev/en/stable/objects.inv
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - mkdocs-click
  - def_list
  - tables
  - toc:
      permalink: "¶"
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tasklist:
      clickable_checkbox: true

nav:
  - Home: index.md
  - Command line interface: reference/cli.md
  - Version history: version_history.md
